### ISSUE TITLE
maybe separate translatedselect and translatedtags

### ISSUE THREAD

**Issue by zonky2** [MetaModels/bundle_translated#3]
maybe separate translatedselect and translatedtags to a separate bundle or install manuell like special packages like filter_register

the two attributes confuse most users who work with translated MM, because they don't know that the untranstated repos do that and they are only for non MM tables

**Comment by discordier** [comment]
Feel free to do so, however it is a bc break then and therefore needs to get a new major number.

On the other hand, I do not like the bundles that much and wanted to get rid of them for a long time so I don't really care that much.
What do you think @stefanheimes

**Comment by zonky2** [comment]
er sagt o.k.

**Comment by zonky2** [comment]
fix https://github.com/MetaModels/bundle_translated/pull/4
